name: node CI

on:
  #Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
   
    - name: Boman SAST
      run: |
        pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==0.12
    - name:  Run a multi-line script
      run: |
        boman-cli-uat -a run -u https://devapi.boman.ai/v2/
